version: '3.6'

services:
  fe:
    build:
      context: ./frontend/wiki-explorer
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./vuejs:/project
      - /project/node_modules
    networks:
      - project_network
      - frontend
    depends_on:
      - be

  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    networks:
      - project_network
      - frontend
networks:
  frontend:
    driver: bridge
  project_network:
    driver: bridge
    external: true