version: '3.6'

services:

  db:
      image: mariadb:11
      ports:
        - "3306:3306"
      environment:
        - MARIADB_USER=thomas
        - MARIADB_PASSWORD=12345
        - MARIADB_ROOT_PASSWORD=12345
      networks:
        - project_network

networks:
  project_network:
    driver: bridge
    external: true

volumes:
  db_data: